Repository KakaoTech-14-All-in-one-move/AIM-14-FE, pull requests merged in 2024-11, with the labels that each got.

#16 Aim 51 implementing the login backend api integration
  package.json
  public/google_login_logo.png
  public/google_login_logo.webp
  src/App.tsx
  src/api/apiClient.ts
  src/api/auth.api.ts
  src/components/Home/Channelbar/ChannelFooter.tsx
  src/components/Home/Channelbar/ChannelList.tsx
  src/components/Home/Channelbar/types.ts
  src/components/Home/ChatArea/ChatInput.tsx
  src/components/Home/ChatArea/Message.tsx
  src/components/Home/ChatArea/MessageList.tsx
  src/components/Home/ChatArea/index.tsx
  src/components/Home/index.tsx
  src/components/Login/DefaultProfileImage.tsx
  src/components/Login/OAuth2Callback.tsx
  src/components/Login/RegisterMember.tsx
  src/components/Login/SocialLoginButton.tsx
  src/components/Login/index.tsx
  src/components/Provider/ToastProvider.tsx
  src/components/Router/AppRoutes.tsx
  src/components/Router/AuthEventHandler.tsx
  src/components/Router/ProtectedRoute.tsx
  src/components/Router/PublicRoute.tsx
  src/hooks/useAuth.ts
  src/index.css
  src/stores/authStore.ts
  src/stores/login.ts
  src/stores/memberStore.ts
  src/stores/messageStore.ts
  src/types/auth.types.ts
  yarn.lock
Labels: refactor, feat

#18 Api client
  src/api/apiClient.ts
Labels: refactor, fix

#20 Aim 68 implement my page
  src/api/auth.api.ts
  src/components/Home/Channelbar/ChannelFooter.tsx
  src/components/Login/DefaultProfileImage.tsx
  src/components/UserSettings/DeleteAccountSection.tsx
  src/components/UserSettings/LogoutSection.tsx
  src/components/UserSettings/ProfileSection.tsx
  src/components/UserSettings/UserInfoSection.tsx
  src/components/UserSettings/UserSettingsModal.tsx
  src/stores/authStore.ts
  tsconfig.app.json
Labels: feat

#12 Aim 37 impl record page
  .env
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/common/icons/big-mic.tsx
  src/common/icons/camera-off.tsx
  src/common/icons/camera-on.tsx
  src/common/icons/cancel.tsx
  src/common/icons/download.tsx
  src/common/icons/feedback.tsx
  src/common/icons/mic.tsx
  src/common/icons/record.png
  src/common/icons/record.tsx
  src/common/icons/share.tsx
  src/common/icons/stop.tsx
  src/components/Home/Channelbar/ChannelContext.tsx
  src/components/Home/Channelbar/ChannelList.tsx
  src/components/Home/Channelbar/types.ts
  src/components/Home/ChatArea/ChatHeader.tsx
  src/components/Login/DefaultProfileImage.tsx
  src/components/Login/OAuth2Callback.tsx
  src/components/Record/AudioWaveform.tsx
  src/components/Record/CameraRecording.tsx
  src/components/Record/Controls.tsx
  src/components/Record/FileUploadBox.tsx
  src/components/Record/ScreenSharing.tsx
  src/components/Record/index.tsx
  src/components/Router/AppRoutes.tsx
  src/components/Video/VideoContent.tsx
  src/components/Video/VideoControls.tsx
  src/components/Video/VideoUserBox.tsx
  src/components/Video/index.tsx
  src/components/Video/types/video.ts
  src/components/Voice/ControlButton.tsx
  src/components/Voice/UserBox.tsx
  src/components/Voice/VoiceContent.tsx
  src/components/Voice/VoiceControls.tsx
  src/components/Voice/index.tsx
  src/components/Voice/types/voice.ts
  src/components/feedback/CategoryIcon.tsx
  src/components/feedback/FeedbackContent.tsx
  src/components/feedback/index.tsx
  src/components/feedback/sections/FeedbackAnalysisSection.tsx
  src/components/feedback/sections/FeedbackHeader.tsx
  src/components/feedback/sections/FeedbackImageSection.tsx
  src/components/feedback/types.ts
  src/hooks/useRecordingStore.ts
  src/hooks/useVoiceChat.ts
  src/main.tsx
  src/services/call/CallProvider.tsx
  src/services/call/callConnection.ts
  src/services/call/constants.ts
  src/services/call/types.ts
  src/services/record/apiService.ts
  yarn.lock
Labels: feat

#27 Aim 139 implement server channel backend integration
  src/api/server.api.ts
  src/components/Home/Sidebar/ContextMenu.tsx
  src/components/Home/Sidebar/SidebarIcon.tsx
  src/components/Home/Sidebar/index.tsx
  src/components/Login/OAuth2Callback.tsx
  src/hooks/useAuth.ts
  src/services/record/apiService.ts
  src/stores/authStore.ts
  src/stores/serverStore.ts
  src/types/auth.types.ts
  src/types/server.ts
Labels: feat

#28 Aim 140 implement server backend logic
  src/components/Home/Channelbar/ChannelFooter.tsx
  src/components/Home/Sidebar/ContextMenu.tsx
  src/components/Home/Sidebar/SidebarIcon.tsx
  src/components/Home/Sidebar/index.tsx
  src/components/Login/SocialLoginButton.tsx
  src/components/UserSettings/ProfileSection.tsx
  src/hooks/useServers.ts
  src/stores/authStore.ts
Labels: feat

#30 Aim 141 implement channel backend logic
  src/api/channelApi.ts
  src/components/Home/Channelbar/ChannelContext.tsx
  src/components/Home/Channelbar/ChannelHeader.tsx
  src/components/Home/Channelbar/ChannelList.tsx
  src/components/Home/Channelbar/types.ts
  src/components/Home/Sidebar/index.tsx
  src/components/Login/OAuth2Callback.tsx
  src/hooks/useAuth.ts
  src/stores/channelStore.ts
  src/stores/serverStore.ts
  src/types/server.ts
Labels: feat

#32 Aim 150 implement detailed error messages
  src/components/Home/Sidebar/index.tsx
  src/components/Login/index.tsx
  src/components/UserSettings/UserSettingsModal.tsx
Labels: refactor
