Repository KakaoTech-14-All-in-one-move/AIM-14-FE, pull requests merged in 2024-12, with the labels that each got.

#36 Aim 179 fix logic as user data is added
  src/components/Login/OAuth2Callback.tsx
  src/hooks/useAuth.ts
  src/stores/authStore.ts
  src/types/auth.types.ts
Labels: refactor, fix

#37 Aim 111 send voice video data
  src/App.tsx
  src/common/icons/record.tsx
  src/components/Home/Channelbar/ChannelContext.tsx
  src/components/Home/Channelbar/ChannelList.tsx
  src/components/Home/Channelbar/index.tsx
  src/components/Home/Sidebar/index.tsx
  src/components/Provider/ChannelNavigationProvider.tsx
  src/components/Provider/ChannelNavigator.ts
  src/components/Video/ControlButton.tsx
  src/components/Video/VideoContent.tsx
  src/components/Video/VideoControls.tsx
  src/components/Video/VideoUserBox.tsx
  src/components/Video/index.tsx
  src/components/Video/types/video.ts
  src/components/Voice/ControlButton.tsx
  src/components/Voice/UserBox.tsx
  src/components/Voice/VoiceContent.tsx
  src/components/Voice/VoiceControls.tsx
  src/components/Voice/index.tsx
  src/components/Voice/types/voice.ts
  src/hooks/useMediaChat.ts
  src/hooks/useMediaConnection.ts
  src/hooks/useVoiceChat.ts
  src/services/call/CallProvider.tsx
  src/services/call/MediaConnectionManager.ts
  src/services/call/UserStateManager.ts
  src/services/call/callConnection.ts
  src/services/call/constants.ts
  src/services/call/socket/callConnection.ts
  src/services/call/socket/types.ts
  src/services/call/types.ts
  src/services/call/webrtc/MediaDevicesManager.ts
  src/services/call/webrtc/MediaServerConnection.ts
  src/services/call/webrtc/types.ts
  src/stores/mediaDeviceStore.ts
  src/stores/useRecordingStore.ts
  src/stores/userChannelStore.ts
  tsconfig.json
Labels: feat

#39 Aim 177 implement chat
  package.json
  src/api/apiClient.ts
  src/api/auth.api.ts
  src/components/Home/Channelbar/ChannelList.tsx
  src/components/Home/Channelbar/index.tsx
  src/components/Home/ChatArea/ChatHeader.tsx
  src/components/Home/ChatArea/ChatInput.tsx
  src/components/Home/ChatArea/Message.tsx
  src/components/Home/ChatArea/MessageList.tsx
  src/components/Home/ChatArea/index.tsx
  src/components/Home/Sidebar/index.tsx
  src/components/Home/index.tsx
  src/components/Login/OAuth2Callback.tsx
  src/components/Router/AppRoutes.tsx
  src/components/UserSettings/UserSettingsModal.tsx
  src/hooks/useAuth.ts
  src/stores/authStore.ts
  src/stores/channelStore.ts
  src/stores/messageStore.ts
  src/stores/webSocketStore.ts
  src/types/auth.types.ts
  src/types/chat.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  yarn.lock
Labels: refactor, feat

#43 Aim 208 hotfix 1 merge conflict
  .env.production
  nginx.conf
  src/components/Home/Channelbar/ChannelList.tsx
  src/components/Record/AudioWaveform.tsx
  src/components/Record/Controls.tsx
  src/components/Record/FileUploadBox.tsx
  src/components/Record/index.tsx
  src/components/Video/VideoUserBox.tsx
  src/components/Voice/UserBox.tsx
  src/components/feedback/FeedbackContent.tsx
  src/components/feedback/VoiceFeedbackContent.tsx
  src/components/feedback/index.tsx
  src/components/feedback/types.ts
  src/services/call/MediaConnectionManager.ts
  src/services/call/UserStateManager.ts
  src/services/call/socket/callConnection.ts
  src/services/call/webrtc/MediaServerConnection.ts
  src/services/record/apiService.ts
  src/stores/userChannelStore.ts
Labels: fix

#47 Aim 217 fix bug
  .env
  .env.development
  public/pitching.site_intro.png
  src/components/Home/Channelbar/ChannelHeader.tsx
  src/components/Home/Channelbar/index.tsx
  src/components/Home/ChatArea/ChatHeader.tsx
  src/components/Home/ChatArea/Message.tsx
  src/components/Home/ChatArea/index.tsx
  src/components/Home/Sidebar/index.tsx
  src/components/Router/AppRoutes.tsx
  src/hooks/useAuth.ts
  src/services/record/apiService.ts
  yarn.lock
Labels: fix
